version: '2'
services:
  redis:
    image: "redis"
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
  rabbit:
    image: "rabbitmq:3-management"
    restart: unless-stopped
    hostname: "rabbit"
    env_file: .env-dev
    ports:
      - 5672:5672
      - 15672:15672
  app:
    build: ../queue
    restart: unless-stopped
    volumes:
      - ../queue:/usr/src/app
    command: ["dev"]
    env_file: .env-dev
    links:
      - redis:redis
      - rabbit:rabbit
      - postgres:postgres
    ports:
      - 33405:33405
  scheduler:
    build: ../queue
    restart: unless-stopped
    volumes:
      - ../queue:/usr/src/app
    env_file: .env-dev
    links:
      - redis:redis
      - rabbit:rabbit
      - postgres:postgres
    command: ["scheduler"]
  queue:
    build: ../queue
    restart: unless-stopped
    volumes:
      - ../queue:/usr/src/app
    env_file: .env-dev
    links:
      - rabbit:rabbit
      - redis:redis
      - postgres:postgres
    ports:
      - 33406:33406
    command: ["queue"]
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: .env-dev
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  live:
    build : ../live
    user: "node"
    working_dir: /home/node/live
    restart: unless-stopped
    env_file:
      - .env-dev
    volumes:
      - ../live/public/config.json:/home/node/live/public/config.json
    links:
      - redis:redis
      - rabbit:rabbit
    ports:
      - 33450:3000
  mariadb:
    image: "mariadb"
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env-dev
  matomo:
    image: "matomo"
    restart: unless-stopped
    volumes:
      - matomo:/var/www/html
    env_file:
      - .env-dev
    links:
      - mariadb:mariadb
    ports:
      - 33460:80
  reverseproxy:
    image: "nginx:alpine"
    restart: unless-stopped
    volumes:
      - ../reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - ../reverseproxy/asset:/var/www/frontage/asset
      - ../reverseproxy/index.html:/var/www/frontage/index.html
    ports:
      - 80:80
      - 443:443
    links:
      - matomo:matomo
      - live:live
      - app:app
      - queue:queue
  artnet:
    build: ../artnet
    restart: unless-stopped
    volumes:
      - ../artnet:/usr/src/app
    env_file: .env-dev
    ports:
      - 6454:6454/udp
    network_mode: "host"
volumes:
  db-data:
  mariadb:
  matomo:
