version: '2'
services:
  redis:
    image: "redis"
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
  rabbit:
    image: "rabbitmq:3-management"
    restart: unless-stopped
    hostname: "rabbit"
    env_file: .env
    ports:
      - 5672:5672
  app:
    build: ../queue
    restart: unless-stopped
    volumes:
      - ../queue:/usr/src/app
    command: ["prod"]
    env_file: .env
    links:
      - redis:redis
      - rabbit:rabbit
      - postgres:postgres
    ports:
      - 33405:33405
  scheduler:
    build: ../queue
    restart: unless-stopped
    volumes:
      - ../queue:/usr/src/app
    env_file: .env
    links:
      - redis:redis
      - rabbit:rabbit
      - postgres:postgres
    command: ["scheduler"]
  queue:
    build: ../queue
    restart: unless-stopped
    volumes:
      - ../queue:/usr/src/app
    env_file: .env
    links:
      - rabbit:rabbit
      - redis:redis
      - postgres:postgres
    command: ["queue"]
  postgres:
    image: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
  live:
    build : ../live
    user: "node"
    working_dir: /home/node/live
    restart: unless-stopped
    env_file:
      - .env
    links:
      - redis:redis
      - rabbit:rabbit
  mariadb:
    image: "mariadb"
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  matomo:
    image: "matomo"
    restart: unless-stopped
    volumes:
      - matomo:/var/www/html
    env_file:
      - .env
    links:
      - mariadb:mariadb
  reverseproxy:
    image: "nginx:alpine"
    restart: unless-stopped
    volumes:
      - ../reverseproxy/nginx.conf:/etc/nginx/nginx.conf
      - ../reverseproxy/asset:/var/www/frontage/asset
      - ../reverseproxy/index.html:/var/www/frontage/index.html
    ports:
      - 80:80
      - 443:443
    links:
      - matomo:matomo
      - live:live
      - app:app
      - queue:queue
  dnsmasq:
    build: ../dnsmasq
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "67:67/tcp"
    restart: unless-stopped
  artnet:
    build: ../artnet
    restart: unless-stopped
    volumes:
      - ../artnet:/usr/src/app
    env_file: .env
    ports:
      - 6454:6454/udp
    network_mode: "host"
volumes:
  db-data:
  mariadb:
  matomo:
