
class Actions:
    QUIT = 'QUIT'
    ACTIVEEVENT = 'ACTIVEEVENT'
    KEYDOWN = 'KEYDOWN'
    KEYUP = 'KEYUP'
    MOUSEMOTION = 'MOUSEMOTION'
    MOUSEBUTTONUP = 'MOUSEBUTTONUP'
    MOUSEBUTTONDOWN = 'MOUSEBUTTONDOWN'
    JOYAXISMOTION = 'JOYAXISMOTION'
    JOYBALLMOTION = 'JOYBALLMOTION'
    JOYHATMOTION = 'JOYHATMOTION'
    JOYBUTTONUP = 'JOYBUTTONUP'
    JOYBUTTONDOWN = 'JOYBUTTONDOWN'
    VIDEORESIZE = 'VIDEORESIZE'
    VIDEOEXPOSE = 'VIDEOEXPOSE'
    USEREVE = 'USEREVENTNT'

    KEYS = 'KEYS'

    K_UP = '^'
    K_DOWN = 'v'
    K_RIGHT = '>'
    K_LEFT = '<'

    UP = 'UP'
    DOWN = 'DOWN'
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
